// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function TestComponent(Props) {
  return React.createElement("div", undefined, "testing");
}

var make = TestComponent;

export {
  make ,
  
}
/* react Not a pure module */
