// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

var mystr = "testing";

function TestComponent$default(Props) {
  return React.createElement("div", undefined, mystr);
}

var $$default = TestComponent$default;

export {
  mystr ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
